services:
  app:
    environment:
      - APP_ENV=LOCAL
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: portfolio-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - app_storage:/var/www/storage
      - app_cache:/var/www/bootstrap/cache
    networks:
      - portfolio
    expose:
      - 9000
    ports:
      - "5173:5173"


  webserver:
    image: nginx:alpine
    container_name: portfolio-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - portfolio

  db:
    image: mysql:8.0
    container_name: portfolio-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - portfolio
    ports:
      - "3307:3306"

networks:
  portfolio:
    driver: bridge

volumes:
  mysql_data:
  app_storage:
  app_cache: